// DPR Labs design-token build — Style Dictionary v4 (DTCG source -> CSS custom properties).
// Emits ONE token file (dist/tokens.css) with :root (dark, default), [data-theme="light"],
// and a prefers-reduced-motion collapse. Also emits flat JSON per mode (for the contrast
// audit) and a Tailwind preset. Values are kept verbatim (only names are transformed) so the
// authoritative hex/clamp/cubic-bezier values are never mangled. Unresolved references throw,
// which is the "0 dangling refs" build proof.

import StyleDictionary from 'style-dictionary';
import { promises as fs } from 'node:fs';

const DIST = 'dist';
const NAME_ONLY = ['name/kebab']; // rename to --kebab-case; do NOT transform values

const banner = (title) =>
  `/* =====================================================================\n` +
  `   DPR Labs — ${title}\n` +
  `   GENERATED by design/build.mjs from tokens/*.json (W3C DTCG).\n` +
  `   Do NOT hand-edit. Edit the DTCG source and rebuild: npm run build\n` +
  `   Tiers: palette (primitive) -> color roles (semantic) -> components.\n` +
  `   ===================================================================== */\n`;

function config({ source, cssFile, selector, jsonFile }) {
  return {
    source,
    log: { warnings: 'warn', errors: 'throw', verbosity: 'verbose' },
    platforms: {
      css: {
        transforms: NAME_ONLY,
        buildPath: `${DIST}/`,
        files: [
          {
            destination: cssFile,
            format: 'css/variables',
            options: { selector, outputReferences: true },
          },
        ],
      },
      json: {
        transforms: NAME_ONLY,
        buildPath: `${DIST}/`,
        files: [{ destination: jsonFile, format: 'json/flat' }],
      },
    },
  };
}

async function build() {
  // Dark / default: primitives + dark semantics + components -> :root
  const dark = new StyleDictionary(
    config({
      source: ['tokens/primitive.json', 'tokens/semantic.json', 'tokens/component.json'],
      cssFile: '_root.css',
      selector: ':root',
      jsonFile: 'tokens.dark.json',
    }),
  );
  await dark.buildAllPlatforms();

  // Light: primitives + light semantics (same paths) -> [data-theme="light"]
  const light = new StyleDictionary(
    config({
      source: ['tokens/primitive.json', 'tokens/semantic.light.json'],
      cssFile: '_light.css',
      selector: '[data-theme="light"]',
      jsonFile: 'tokens.light.json',
    }),
  );
  await light.buildAllPlatforms();

  // Merge the two CSS layers into the single canonical token file.
  const root = await fs.readFile(`${DIST}/_root.css`, 'utf8');
  const lightCss = await fs.readFile(`${DIST}/_light.css`, 'utf8');

  const reduced =
    `\n/* Reduced-motion: collapse every motion token so all durations run instantly. */\n` +
    `@media (prefers-reduced-motion: reduce) {\n` +
    `  :root {\n` +
    `    --dur-instant: 0.01ms;\n` +
    `    --dur-fast: 0.01ms;\n` +
    `    --dur-base: 0.01ms;\n` +
    `    --dur-slow: 0.01ms;\n` +
    `    --dur-cinematic: 0.01ms;\n` +
    `  }\n}\n`;

  const merged = `${banner('Unified Design Tokens · tokens.css')}\n${root}\n${lightCss}${reduced}`;
  await fs.writeFile(`${DIST}/tokens.css`, merged, 'utf8');

  // Clean up the two intermediate layer files.
  await fs.rm(`${DIST}/_root.css`);
  await fs.rm(`${DIST}/_light.css`);

  // Tailwind preset: bind theme keys to the CSS custom properties (mode-adaptive).
  const flat = JSON.parse(await fs.readFile(`${DIST}/tokens.dark.json`, 'utf8'));
  const pick = (prefix) =>
    Object.keys(flat)
      .filter((k) => k.startsWith(prefix))
      .reduce((o, k) => {
        o[k.slice(prefix.length)] = `var(--${k})`;
        return o;
      }, {});
  const preset = {
    theme: {
      extend: {
        colors: pick('color-'),
        borderRadius: pick('radius-'),
        spacing: pick('space-'),
        fontFamily: { display: 'var(--font-display)', body: 'var(--font-body)', mono: 'var(--font-mono)' },
        transitionTimingFunction: pick('ease-'),
        transitionDuration: pick('dur-'),
        zIndex: pick('z-'),
      },
    },
  };
  await fs.writeFile(
    `${DIST}/tokens.tailwind.cjs`,
    `// GENERATED by design/build.mjs — Tailwind preset bound to CSS custom properties.\nmodule.exports = ${JSON.stringify(preset, null, 2)};\n`,
    'utf8',
  );

  const varCount = (root.match(/--/g) || []).length;
  console.log(`\nOK  wrote ${DIST}/tokens.css  (${varCount} custom properties in :root)`);
  console.log(`OK  wrote ${DIST}/tokens.dark.json, ${DIST}/tokens.light.json, ${DIST}/tokens.tailwind.cjs`);
}

build().catch((err) => {
  console.error('\nBUILD FAILED:', err.message);
  process.exit(1);
});
